openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
paths:
  /v1/clients:
    get:
      summary: Retrieve a list of clients
      parameters:
        - name: comptes
          in: query
          description: Filter clients based on whether they have associated user accounts.
          schema:
            type: string
            enum: [oui, non]
        - name: active
          in: query
          description: Filter clients based on the status of their associated user accounts.
          schema:
            type: string
            enum: [oui, non]
      responses:
        '200':
          description: List of clients retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Client'
        '403':
          description: Forbidden (permission denied)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    post:
      summary: Create a new client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                surname:
                  type: string
                adresse:
                  type: string
                telephone:
                  type: string
                photo:
                  type: string
                user:
                  type: object
                  properties:
                    nom:
                      type: string
                    prenom:
                      type: string
                    login:
                      type: string
                    password:
                      type: string
                    role_id:
                      type: integer
                    etat:
                      type: string
              required:
                - surname
                - adresse
                - telephone
      responses:
        '201':
          description: Client created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Client'
                  message:
                    type: string
        '400':
          description: Bad request (validation error)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '403':
          description: Forbidden (permission denied)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /v1/clients/{id}:
    get:
      summary: Retrieve a specific client
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the client to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Client retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Client'
                  message:
                    type: string
        '403':
          description: Forbidden (permission denied)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Client not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    put:
      summary: Update a specific client
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the client to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                surname:
                  type: string
                adresse:
                  type: string
                telephone:
                  type: string
              required:
                - surname
                - adresse
                - telephone
      responses:
        '200':
          description: Client updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Client'
                  message:
                    type: string
        '403':
          description: Forbidden (permission denied)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Client not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    delete:
      summary: Delete a specific client
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the client to delete
          schema:
            type: string
      responses:
        '200':
          description: Client deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '403':
          description: Forbidden (permission denied)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Client not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /v1/clients/telephone:
    post:
      summary: Retrieve a client by phone number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                telephone:
                  type: string
              required:
                - telephone
      responses:
        '200':
          description: Client retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Client'
                  message:
                    type: string
        '400':
          description: Bad request (validation error)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Client not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /v1/clients/register:
    post:
      summary: Add an account to an existing client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                surname:
                  type: string
                user:
                  type: object
                  properties:
                    nom:
                      type: string
                    prenom:
                      type: string
                    login:
                      type: string
                    password:
                      type: string
                    role_id:
                      type: integer
                    etat:
                      type: string
              required:
                - surname
                - user
      responses:
        '201':
          description: Account added to the client successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Client'
                  message:
                    type: string
        '400':
          description: Bad request (validation error)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '403':
          description: Forbidden (permission denied)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Client not found or account already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Client:
      type: object
      properties:
        id:
          type: integer
        surname:
          type: string
        adresse:
          type: string
        telephone:
          type: string
        photo:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
